# change the followings to match your Github username and repo name
baseurl: "/godot-torrent" # the name of your github repo
url: "https://nodotproject.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Godot-Torrent"
description: A comprehensive BitTorrent GDExtension for Godot 4, providing full protocol functionality with native C++ performance.

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: NodotProject
author-bio: false
author-image: false

# navigation menu
show-nav-menu: true

nav-menu:
- text: Getting Started
  permalink: getting-started
- text: Tutorials
  permalink: tutorial-basic-download
- text: Guides
  permalink: guide-advanced-config
- text: API Reference
  permalink: api-reference

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: false
linkedin: false
medium: false
google-scholar: false
email: false

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
    - jekyll-optional-front-matter
    - jekyll-relative-links

# Configure optional front matter to work like GitHub Pages
optional_front_matter:
  enabled: true

# Configure relative links to convert .md to .html
relative_links:
  enabled: true
  collections: false

# Set default layout for all pages (except index which uses home layout)
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
